modified4

diff --git a/.github/workflows/pushallcode.yml b/.github/workflows/pushallcode.yml
--- a/.github/workflows/pushallcode.yml
+++ b/.github/workflows/pushallcode.yml
@@ -9,5 +9,9 @@ jobs:
   my-second-job:
     runs-on: ubuntu-latest
     steps:
+       - name: Failed Job
+         run: |
+           echo "I will fail"
+           exit 1
        - name: bye bye world
          run: echo "bye bye world"
